services:
  - type: web
    name: reconhecimento-facial-api
    runtime: python
    # pythonVersion: "3.11" # Você pode especificar a versão do Python se necessário, ex: 3.9, 3.10, 3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: echo "====== O START COMMAND DO RENDER.YAML FOI EXECUTADO ======" && ls -la && gunicorn --workers 1 --threads 2 --timeout 120 app:app
    envVars: # Melhor forma de definir variáveis de ambiente
      - key: PYTHON_VERSION # Exemplo, se precisar forçar a versão do Python
        value: "3.11"      # Ajuste conforme a versão que suas dependências precisam
      - key: FLASK_ENV      # Embora Gunicorn não use diretamente, pode ser útil para extensões Flask
        value: production
    plan: free # Ou o plano que você estiver usando
    autoDeploy: true
    healthCheckPath: / # Rota para o Render verificar se a aplicação está saudável
    # region: frankfurt # Opcional: Especifique a região se necessário, ex: oregon, frankfurt
